spring.application.name=accounting-manager-api-test

SPRING_EUREKA_URL=http://localhost:8123/eureka
eureka.client.enabled=false
spring.cloud.discovery.enabled=false

jwt.secret=secret-key
jwt.issuer=login-service
jwt.public=/**

services.sales.base-url=http://localhost:8082/api/v1/sales
services.invoices.base-url=http://localhost:8087/api/v1/invoices
services.users.base-url=http://localhost:8081/api/v1/users