# Documentation Metadata
springdoc.openapi.info.title=Accounting Manager Microservice API
springdoc.openapi.info.version=v0.1
springdoc.openapi.info.description=Microservicio orquestador contable. \
                                   Coordina sales-api, invoice-api y users-api.
